---
- hosts: localhost
  become: false
  tasks:
    - name: Generate kubectl file
      environment:
        KUBECONFIG: /ansinetes/kubeconfig.yaml
      shell: |
        kubectl config set-cluster ansinetes \
          --server=https://{{hostvars[groups['apiservers'][0]].ansible_host}}:6443 \
          --insecure-skip-tls-verify=true && \
        kubectl config set-credentials admin \
          --client-key=/ansinetes/security/certs/admin-key.pem \
          --client-certificate=/ansinetes/security/certs/admin.pem \
          --embed-certs=true && \
        kubectl config set-context ansinetes \
          --cluster=ansinetes \
          --user=admin && \
        kubectl config use-context ansinetes

    - name : Generate ssh_config
      template:
        mode: go-rwx
        dest: /ansinetes/tmp/ssh_config
        src: /etc/ansible/coreos-config/ssh_config.j2

    - name: Create ovpn client profile
      template:
      args:
        src: /etc/ansible/k8s-config/addons/ovpn-client.conf.j2
        dest: /ansinetes/ovpn-client.conf