---
- hosts: localhost

  tasks:
    - name: Generate kubectl file
      become_user: ansinetes
      environment:
        KUBECONFIG: /ansinetes/kubeconfig.yaml
      shell: |
        kubectl config set-cluster ansinetes \
          --server=https://{{hostvars[groups['ingress-edges'][0]].ansible_host}}:6443 \
          --insecure-skip-tls-verify=true && \
        kubectl config set-credentials admin \
          --client-key=/ansinetes/security/certs/admin-key.pem \
          --client-certificate=/ansinetes/security/certs/admin.pem \
          --embed-certs=true && \
        kubectl config set-context ansinetes \
          --cluster=ansinetes \
          --user=admin && \
        kubectl config use-context ansinetes

    - name : Generate ssh_config
      become_user: ansinetes
      template:
        mode: go-rwx
        dest: /ansinetes/ssh_config
        src: /etc/ansible/coreos-config/ssh_config.j2
