---
- name: Start kubernetes

  hosts: all

  vars_files:
    - /etc/ansible/k8s-config/vars.yaml

  vars:
    addons:
      - dashboard-controller.yaml
      - dashboard-service.yaml
      - kubedns-sa.yaml
      - kubedns-controller.yaml
      - kubedns-svc.yaml
      - heapster-controller.yaml
      - heapster-service.yaml
      - ovpn-secrets.yaml
      - ovpn-controller.yaml
      - ovpn-service.yaml
      - nginx-ingress.yaml
      - default-backend-service.yaml
      - default-backend.yaml
      - registry-rc.yaml
      - registry-svc.yaml
      - registry-ds.yaml

  tasks:
    - name: Start apiserver
      service:
      args:
        name: kube-apiserver.service
        state: "{%if inventory_hostname in groups['apiservers']%}started{%else%}stopped{%endif%}"
        enabled: "{%if inventory_hostname in groups['apiservers']%}yes{%else%}no{%endif%}"

    - name: Start scheduler
      service:
      args:
        name: kube-scheduler.service
        state: "{%if inventory_hostname in groups['schedulers']%}started{%else%}stopped{%endif%}"
        enabled: "{%if inventory_hostname in groups['schedulers']%}yes{%else%}no{%endif%}"

    - name: Start controller-manager
      service:
      args:
        name: kube-controller-manager.service
        state: "{%if inventory_hostname in groups['controller-managers']%}started{%else%}stopped{%endif%}"
        enabled: "{%if inventory_hostname in groups['controller-managers']%}yes{%else%}no{%endif%}"

    - name: Start kubelet
      service:
      args:
        name: kubelet.service
        state: "{%if inventory_hostname in groups['kubelets']%}started{%else%}stopped{%endif%}"
        enabled: "{%if inventory_hostname in groups['kubelets']%}yes{%else%}no{%endif%}"

    - name: Start proxy
      service:
      args:
        name: kube-proxy.service
        state: "{%if inventory_hostname in groups['kubelets']%}started{%else%}stopped{%endif%}"
        enabled: "{%if inventory_hostname in groups['kubelets']%}yes{%else%}no{%endif%}"

    - name: Start apiserver-lb
      service: name=apiserver-lb.service state=started enabled=yes

    - name: Render cluster add-ons locally
      delegate_to: localhost
      when: inventory_hostname == groups.apiservers[0]
      become: False
      template:
      args:
        src: /etc/ansible/k8s-config/addons/{{item}}.j2
        dest: /tmp/ansible/{{item}}
      with_items: "{{addons}}"

    - name: Start add-ons
      shell: "/opt/kubernetes/bin/kubectl {{kubectl_params}} create -f /etc/kubernetes/addons/{{item}} || echo Maybe already started"
      when: inventory_hostname == groups.apiservers[0]
      with_items: "{{addons}}"
