---
- name: Create k8s config files

  hosts: all

  vars_files:
    - /etc/ansible/k8s-config/vars.yaml

  tasks:
    - name: Stop services
      service:
      args:
        name: "{{item}}"
        state: stopped
      with_items:
        - kube-apiserver.service
        - kube-controller-manager.service
        - kubelet.service
        - kube-proxy.service
        - kube-scheduler.service
        - apiserver-lb.service
