---

kubernetes_install:
  version: v1.5.7
  sha256: sha256:ae18d659811da316d4a8bbdce15c4396fdee0068f9d3247a72c3a23433fee44c

######### Not customizable, just reducing duplication
etcdctl_params: --ca-file /etc/ssl/etcd/ca.pem --key-file /etc/ssl/etcd/client-key.pem --cert-file /etc/ssl/etcd/client.pem --endpoint https://localhost:2379
locksmithctl_params: --etcd-cafile /etc/ssl/etcd/ca.pem --etcd-keyfile /etc/ssl/etcd/client-key.pem --etcd-certfile /etc/ssl/etcd/client.pem --endpoint https://localhost:2379
kubectl_params: --kubeconfig=/etc/kubernetes/kubelet/config
