---
# kublet-wrapper is used
# check https://quay.io/repository/coreos/hyperkube?tab=tags for valid tags
kubernetes_install:
  version: v1.6.8
  tag: v1.6.8_coreos.0

helm_install:
  version: v2.5.1

######### Not customizable, just reducing duplication
etcdctl_params: --ca-file /etc/ssl/etcd/ca.pem --key-file /etc/ssl/etcd/client-key.pem --cert-file /etc/ssl/etcd/client.pem --endpoint https://localhost:2379
locksmithctl_params: --etcd-cafile /etc/ssl/etcd/ca.pem --etcd-keyfile /etc/ssl/etcd/client-key.pem --etcd-certfile /etc/ssl/etcd/client.pem --endpoint https://localhost:2379
kubectl_params: --kubeconfig=/etc/kubernetes/conf/kubelet.config
