---
galaxy_info:
  author: Antti J. Salminen
  description: Manages /etc/hosts and /etc/hostname with templates.
  company: Libraries.fi / Helsinki city library
  license: MIT
  min_ansible_version: 1.5
  platforms:
    - name: EL
      versions:
        - all
    - name: GenericUNIX
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: Amazon
      versions:
        - all
    - name: GenericBSD
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: SLES
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - networking
    - system

dependencies: []
